# Generated by Django 4.1.1 on 2022-09-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
