# Generated by Django 4.1.1 on 2022-10-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0004_post_likes_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
