# Generated by Django 4.1.1 on 2022-10-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
