# Generated by Django 4.1.1 on 2022-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0012_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
