# Generated by Django 4.1.1 on 2022-11-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0015_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
